<?php include 'common-function.php';?>
<?php	
	$date = new DateTime(null);

	$minute = $date->format('i');
	$startTime = 0;
	$hour = 6;
	$startTime = $date->getTimestamp()-((24*60)+$minute)*60-$date->format('s');
	
	//session_unset();
	
	if (!isset($_SESSION['symbolTimestam4h']) || $_SESSION['symbolTimestam4h'] != $startTime) {
		//$symbolStr = 'ETHBTC,LTCBTC,BNBBTC,NEOBTC,GASBTC,MCOBTC,WTCBTC,LRCBTC,QTUMBTC,YOYOBTC,OMGBTC,ZRXBTC,STRATBTC,SNGLSBTC,BQXBTC,KNCBTC,FUNBTC,SNMBTC,IOTABTC,LINKBTC,XVGBTC,MDABTC,MTLBTC,,EOSBTC,SNTBTC,ETCBTC,MTHBTC,ENGBTC,DNTBTC,ZECBTC,BNTBTC,ASTBTC,DASHBTC,OAXBTC,BTGBTC,EVXBTC,REQBTC,VIBBTC,TRXBTC,POWRBTC,ARKBTC,XRPBTC,ENJBTC,STORJBTC,,KMDBTC,RCNBTC,NULSBTC,RDNBTC,XMRBTC,DLTBTC,AMBBTC,BATBTC,BCPTBTC,ARNBTC,GVTBTC,CDTBTC,GXSBTC,POEBTC,QSPBTC,BTSBTC,XZCBTC,LSKBTC,TNTBTC,FUELBTC,MANABTC,BCDBTC,DGDBTC,ADXBTC,ADABTC,PPTBTC,CMTBTC,XLMBTC,CNDBTC,LENDBTC,WABIBTC,TNBBTC,WAVESBTC,GTOBTC,ICXBTC,OSTBTC,ELFBTC,AIONBTC,NEBLBTC,BRDBTC,EDOBTC,NAVBTC,LUNBTC,APPCBTC,VIBEBTC,RLCBTC,INSBTC,PIVXBTC,IOSTBTC,STEEMBTC,NANOBTC,VIABTC,BLZBTC,AEBTC,NCASHBTC,POABTC,ZILBTC,ONTBTC,STORMBTC,XEMBTC,WANBTC,WPRBTC,QLCBTC,SYSBTC,GRSBTC,,GNTBTC,LOOMBTC,REPBTC,ZENBTC,SKYBTC,CVCBTC,THETABTC,IOTXBTC,QKCBTC,AGIBTC,NXSBTC,DATABTC,SCBTC,NPXSBTC,KEYBTC,NASBTC,MFTBTC,DENTBTC,ARDRBTC,HOTBTC,VETBTC,DOCKBTC,POLYBTC,HCBTC,GOBTC,RVNBTC,DCRBTC,MITHBTC,BCHABCBTC,,RENBTC,BTTBTC,ONGBTC,FETBTC,CELRBTC,MATICBTC,ATOMBTC,PHBBTC,TFUELBTC';
		$symbolStr = 'ETHBTC,LTCBTC,BNBBTC';
		//',NEOBTC,GASBTC,BTCUSDT,ETHUSDT,MCOBTC,WTCBTC,LRCBTC,QTUMBTC,YOYOBTC,OMGBTC,ZRXBTC,STRATBTC,SNGLSBTC,BQXBTC,KNCBTC,FUNBTC,SNMBTC,IOTABTC,LINKBTC,XVGBTC,MDABTC,MTLBTC,,EOSBTC,SNTBTC,ETCBTC,MTHBTC,ENGBTC,DNTBTC,ZECBTC,BNTBTC,ASTBTC,DASHBTC,OAXBTC,BTGBTC,EVXBTC,REQBTC,VIBBTC,TRXBTC,POWRBTC,ARKBTC,XRPBTC,ENJBTC,STORJBTC,BNBUSDT,,KMDBTC,RCNBTC,NULSBTC,RDNBTC,XMRBTC,DLTBTC,AMBBTC,BATBTC,BCPTBTC,ARNBTC,GVTBTC,CDTBTC,GXSBTC,NEOUSDT,POEBTC,QSPBTC,BTSBTC,XZCBTC,LSKBTC,TNTBTC,FUELBTC,MANABTC,BCDBTC,DGDBTC,ADXBTC,ADABTC,PPTBTC,CMTBTC,XLMBTC,CNDBTC,LENDBTC,WABIBTC,LTCUSDT,TNBBTC,WAVESBTC,GTOBTC,ICXBTC,OSTBTC,ELFBTC,AIONBTC,NEBLBTC,BRDBTC,EDOBTC,NAVBTC,LUNBTC,APPCBTC,VIBEBTC,RLCBTC,INSBTC,PIVXBTC,IOSTBTC,STEEMBTC,NANOBTC,VIABTC,BLZBTC,AEBTC,NCASHBTC,POABTC,ZILBTC,ONTBTC,STORMBTC,QTUMUSDT,XEMBTC,WANBTC,WPRBTC,QLCBTC,SYSBTC,GRSBTC,ADAUSDT,,GNTBTC,LOOMBTC,XRPUSDT,REPBTC,ZENBTC,SKYBTC,EOSUSDT,CVCBTC,THETABTC,TUSDUSDT,IOTAUSDT,XLMUSDT,IOTXBTC,QKCBTC,AGIBTC,NXSBTC,DATABTC,ONTUSDT,TRXUSDT,ETCUSDT,ICXUSDT,SCBTC,NPXSBTC,KEYBTC,NASBTC,MFTBTC,DENTBTC,ARDRBTC,NULSUSDT,HOTBTC,VETBTC,VETUSDT,DOCKBTC,POLYBTC,HCBTC,GOBTC,PAXUSDT,RVNBTC,DCRBTC,MITHBTC,BCHABCBTC,,BCHABCUSDT,RENBTC,USDCUSDT,LINKUSDT,WAVESUSDT,BTTBTC,BTTUSDT,USDSUSDT,ONGBTC,ONGUSDT,HOTUSDT,ZILUSDT,ZRXUSDT,FETBTC,FETUSDT,BATUSDT,XMRUSDT,ZECUSDT,IOSTUSDT,CELRBTC,CELRUSDT,DASHUSDT,NANOUSDT,OMGUSDT,THETAUSDT,ENJUSDT,MITHUSDT,MATICBTC,MATICUSDT,ATOMBTC,ATOMUSDT,PHBBTC,TFUELBTC,TFUELUSDT';
		$symbolList = explode(',', $symbolStr);
		
		$numberAds = 100000000;
		$_SESSION['symbolTimestam4h'] = $startTime;
		foreach ($symbolList as $symbol) {
			$url = 'https://www.binance.com/api/v1/klines?symbol='.$symbol.'&interval=4h&startTime='.$startTime.'000&limit=6';
			echo $url.'-----';
			$dataResp = json_decode(CallAPI('GET', $url));

			$date = new DateTime();
			$data = $symbol.': ';
			foreach ($dataResp as $item) {
				if (floatval($item[1]) > floatval($item[4]))
				{
					$data = $data.'-<font color="red">Đỏ</font>';
				} else {
					$data = $data.'-<font color="blue">Xanh</font>';
				}
			}
			echo $data.'<br />';
			
		}
	}
?>